spring:
  datasource:
#    url: "jdbc:mysql://localhost:3306/library"
    # JavaDBConnector: db종류는 mysql, 컴퓨터는 localhost, 사용할 db는 library
    username: "root"
    password: "Dydals123!"
    driver-class-name: com.mysql.cj.jdbc.Driver
    # db에 접근할 떄 사용할 프로그램